### ISSUE TITLE
Improve xpaths in joomla installer to avoid selenium errors

### ISSUE THREAD

**Issue by javigomez** [joomla-projects/joomla-browser#67]
Despite it works, selenium reports many errors due to Codeception heuristics trying to locate elements:

```
10:13:04.282 INFO - Done: [find elements: By.linkText: Install]
10:13:04.284 INFO - Executing: [click: 30 [[FirefoxDriver: firefox on MAC (29d41667-3048-714b-9f55-ea96aeee4067)] -> link text: Install]])
10:13:04.376 INFO - Done: [click: 30 [[FirefoxDriver: firefox on MAC (29d41667-3048-714b-9f55-ea96aeee4067)] -> link text: Install]]
10:13:04.379 INFO - Executing: [find element: By.xpath: //h3])
10:13:04.570 INFO - Done: [find element: By.xpath: //h3]
10:13:04.572 INFO - Executing: [get text: 27 [[FirefoxDriver: firefox on MAC (29d41667-3048-714b-9f55-ea96aeee4067)] -> xpath: //h3]])
10:13:05.132 WARN - Exception thrown
org.openqa.selenium.StaleElementReferenceException: Element is no longer attached to the DOM
Command duration or timeout: 181 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.46.0', revision: '87c69e2', time: '2015-06-04 16:16:47'
System info: host: 'JAVI.local', ip: '192.168.1.128', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.6.0_65'
Session ID: 29d41667-3048-714b-9f55-ea96aeee4067
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=MAC, acceptSslCerts=true, javascriptEnabled=true, browserName=firefox, rotatable=false, locationContextEnabled=true, version=41.0.1, cssSelectorsEnabled=true, databaseEnabled=true, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, applicationCacheEnabled=true, takesScreenshot=true}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:605)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:269)
	at org.openqa.selenium.remote.RemoteWebElement.getText(RemoteWebElement.java:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement$1.invoke(EventFiringWebDriver.java:332)
	at com.sun.proxy.$Proxy2.getText(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.getText(EventFiringWebDriver.java:382)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.openqa.selenium.remote.server.KnownElements$1.invoke(KnownElements.java:64)
	at com.sun.proxy.$Proxy3.getText(Unknown Source)
	at org.openqa.selenium.remote.server.handler.GetElementText.call(GetElementText.java:30)
	at org.openqa.selenium.remote.server.handler.GetElementText.call(GetElementText.java:1)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:176)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
Caused by: org.openqa.selenium.StaleElementReferenceException: Element is no longer attached to the DOM
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.46.0', revision: '87c69e2', time: '2015-06-04 16:16:47'
System info: host: 'JAVI.local', ip: '192.168.1.128', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.6.0_65'
Driver info: driver.version: unknown
	at <anonymous class>.fxdriver.cache.getElementAt(resource://fxdriver/modules/web-element-cache.js:8984)
	at <anonymous class>.Utils.getElementAt(file:///var/folders/41/bbd356hs31q2130rf9vylbq40000gn/T/anonymous7625181232791055018webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:8574)
	at <anonymous class>.WebElement.getElementText(file:///var/folders/41/bbd356hs31q2130rf9vylbq40000gn/T/anonymous7625181232791055018webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:11722)
	at <anonymous class>.DelayedCommand.prototype.executeInternal_/h(file:///var/folders/41/bbd356hs31q2130rf9vylbq40000gn/T/anonymous7625181232791055018webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12282)
	at <anonymous class>.DelayedCommand.prototype.executeInternal_(file:///var/folders/41/bbd356hs31q2130rf9vylbq40000gn/T/anonymous7625181232791055018webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12287)
	at <anonymous class>.DelayedCommand.prototype.execute/<(file:///var/folders/41/bbd356hs31q2130rf9vylbq40000gn/T/anonymous7625181232791055018webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12229)
10:13:05.136 WARN - Exception: Element is no longer attached to the DOM
For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
Build info: version: '2.46.0', revision: '87c69e2', time: '2015-06-04 16:16:47'
System info: host: 'JAVI.local', ip: '192.168.1.128', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.6.0_65'
Driver info: driver.version: unknown
10:13:05.403 INFO - Executing: [find element: By.xpath: //h3])
10:13:05.429 INFO - Done: [find element: By.xpath: //h3]
10:13:05.432 INFO - Executing: [get text: 31 [[FirefoxDriver: firefox on MAC (29d41667-3048-714b-9f55-ea96aeee4067)] -> xpath: //h3]])
10:13:05.464 INFO - Done: [get text: 31 [[FirefoxDriver: firefox on MAC (29d41667-3048-714b-9f55-ea96aeee4067)] -> xpath: //h3]]
10:13:05.717 INFO - Executing: [find element: By.xpath: //h3])
```

I'm sure we can improve the locators to avoid errors.

**Comment by redJOHNNY** [comment]
This is a very low priority issue. Closing. We will reopen if needed.

**Comment by redJOHNNY** [comment]
This is a very low priority issue. Closing. We will reopen if needed.

**Comment by javigomez** [comment]
This is a very low priority issue. Closing. We will reopen if needed.

**Comment by javigomez** [comment]
This is a very low priority issue. Closing. We will reopen if needed.
